"""create tb message

Revision ID: 1ce3d0692999
Revises: 39e2a33e4f0c
Create Date: 2022-11-21 22:30:55.690789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ce3d0692999'
down_revision = '39e2a33e4f0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_msg', sa.String(length=255), nullable=False),
    sa.Column('bot_response', sa.String(length=255), nullable=False),
    sa.Column('user_timestamp', sa.DateTime(), nullable=True),
    sa.Column('bot_timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
